name: 'gke-argo'
description: Trigger an Argo Workflow on GKE
author: Hamel Husain
inputs:
  argo_uri:
    description: The endpoint where your Argo UI is hosted.  This is used to build the link for dashboard of unique runs. 
    required: true
  application_credentials:
    description: base64 encoded GCP application credentials (https://cloud.google.com/sdk/docs/authorizing)
    require: true
  project_id:
    description: name of the GCP Project where the GKE K8s cluster resides.
    require: true
  location-zone:
    description: The location-zone where your GKE K8s cluster resides, for example `us-west1-a`
    require: true
  cluster_name:
    description: the name of your GKE K8s cluster
    require: true
  workflow_yaml:
    description: the YAML file that describes the workflow you want to run on Argo.
    require: true
outputs:
  WORKFLOW_URL:
    description: URL that is a link to the current run in Argo.
branding:
  color: 'blue'
  icon: 'upload-cloud'
runs:
  using: 'docker'
  image: 'Dockerfile'